### ISSUE TITLE
Possible future server outage

### ISSUE THREAD

**Issue by amazinigmech2418** [ateesdalejr/maildiscuss#7]
In the future, there will probably be more users. If that happens, the PHP servers could overload and break. To prevent that, I suggest using JS API to communicate with Scratch cloud data in a project. Then, you wouldn't have to worry about a server outage. Also, you could make it available to Scratchers who don't know the website with that. I think you'd need node.js, but it would still be client-side.

**Comment by ateesdalejr** [comment]
I really would rather be using PHP than really ugly node for something like this. So PHP is a necessary evil for now. If I had the time I'd probably try to rewrite this in C or something more efficient than node or PHP.

 I've already gotten in trouble for making a dynamic signature script a while a go... So, I'm pretty sure the ST wouldn't like me abusing the cloud as a back end for my own website. I'm banned from the Scratch website as well, so access to cloud data is probably a no can do.

**Comment by csf30816** [comment]
We will **have** to switch servers eventually but are sticking with PHP. The reason a server switch is necessary for the future is the fact that Free VistaPanel is not good for large-scale applications since the page view limit of 50000 a day. And this really has nothing to do with Scratch as @TheUltimatum previously stated. And because of this, we should not send to the Scratch Cloud even though it is easier and it is possible. Also, NodeJS would not be necessary as you just communicate with the server via a JS WebSocket.

**Comment by ateesdalejr** [comment]
How is the page view limit calculated? I've noticed the page is creating several cookies that aren't specified in my code. One of which is named `__test` and contains a hash of some sort.
